// GENERATED by tools/build-mdi-glyphs.py — do not edit by hand.
// Material Design Icons @mdi/font@7.4.47. Rerun the script to change the set.
#pragma once

#include <cstdint>

namespace esphome {
namespace ha_panel {

struct MdiGlyph {
  const char *name;   // mdi name without the 'mdi:' prefix
  uint32_t codepoint; // Private Use Area codepoint baked into mdi_icons font
};

// Sorted-by-insertion name->codepoint table. Linear scan is fine — set is small
// and resolution is cached per entity after first render.
static const MdiGlyph MDI_GLYPHS[] = {
    {"lightbulb", 0xF0335},
    {"toggle-switch", 0xF0521},
    {"fan", 0xF0210},
    {"window-shutter", 0xF111C},
    {"lock", 0xF033E},
    {"thermostat", 0xF0393},
    {"speaker", 0xF04C3},
    {"palette", 0xF03D8},
    {"script-text-play", 0xF1727},
    {"robot", 0xF06A9},
    {"gesture-tap-button", 0xF12A8},
    {"numeric", 0xF03A0},
    {"format-list-bulleted", 0xF0279},
    {"gauge", 0xF029A},
    {"checkbox-marked-circle-outline", 0xF0134},
    {"lightbulb-multiple", 0xF1255},
    {"lightbulb-on", 0xF06E8},
    {"lamp", 0xF06B5},
    {"desk-lamp", 0xF095F},
    {"ceiling-light", 0xF0769},
    {"floor-lamp", 0xF08DD},
    {"string-lights", 0xF12BA},
    {"led-strip-variant", 0xF1051},
    {"wall-sconce", 0xF091C},
    {"toggle-switch-off", 0xF0522},
    {"power", 0xF0425},
    {"power-plug", 0xF06A5},
    {"power-socket-us", 0xF07E9},
    {"fan-off", 0xF081D},
    {"ceiling-fan", 0xF1797},
    {"ceiling-fan-light", 0xF1798},
    {"lock-open", 0xF033F},
    {"lock-alert", 0xF08EE},
    {"window-shutter-open", 0xF111E},
    {"blinds", 0xF00AC},
    {"blinds-open", 0xF1011},
    {"curtains", 0xF1846},
    {"garage", 0xF06D9},
    {"garage-open", 0xF06DA},
    {"gate", 0xF0299},
    {"gate-open", 0xF116A},
    {"air-conditioner", 0xF001B},
    {"radiator", 0xF0438},
    {"fireplace", 0xF0E2E},
    {"heat-pump", 0xF1A43},
    {"weather-sunny", 0xF0599},
    {"weather-cloudy", 0xF0590},
    {"weather-rainy", 0xF0597},
    {"television", 0xF0502},
    {"speaker-multiple", 0xF0D38},
    {"music", 0xF075A},
    {"volume-high", 0xF057E},
    {"volume-off", 0xF0581},
    {"thermometer", 0xF050F},
    {"water-percent", 0xF058E},
    {"motion-sensor", 0xF0D91},
    {"door", 0xF081A},
    {"door-open", 0xF081C},
    {"window-closed", 0xF05AE},
    {"window-open", 0xF05B1},
    {"leak", 0xF0DD7},
    {"smoke-detector", 0xF0392},
    {"battery", 0xF0079},
    {"play", 0xF040A},
    {"cog", 0xF0493},
    {"robot-outline", 0xF167A},
    {"home", 0xF02DC},
    {"alert", 0xF0026},
    {"alert-circle", 0xF0028},
    {"refresh", 0xF0450},
    {"checkbox-blank-circle-outline", 0xF0130},
    {"help-circle", 0xF02D7},
};
static const int MDI_GLYPH_COUNT = 72;

// Fallback glyph when a resolved name is not in the baked set above.
static const uint32_t MDI_FALLBACK_CP = 0xF02D7;  // mdi:help-circle

struct DomainIcon {
  const char *domain;
  const char *icon;  // mdi name, must appear in MDI_GLYPHS
};
// Step 2 of the resolution chain: domain -> default mdi name.
static const DomainIcon MDI_DOMAIN_DEFAULTS[] = {
    {"light", "lightbulb"},
    {"switch", "toggle-switch"},
    {"input_boolean", "toggle-switch"},
    {"fan", "fan"},
    {"cover", "window-shutter"},
    {"lock", "lock"},
    {"climate", "thermostat"},
    {"media_player", "speaker"},
    {"scene", "palette"},
    {"script", "script-text-play"},
    {"automation", "robot"},
    {"button", "gesture-tap-button"},
    {"number", "numeric"},
    {"select", "format-list-bulleted"},
    {"sensor", "gauge"},
    {"binary_sensor", "checkbox-marked-circle-outline"},
};
static const int MDI_DOMAIN_DEFAULT_COUNT = 16;

}  // namespace ha_panel
}  // namespace esphome
